#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 3.6

services: postgresql

env:
  - DJANGO=1.4.1

before_install:
  - export DJANGO_SETTINGS_MODULE=crux.settings
  - export PYTHONPATH=$HOME/nebigdatahub/crux
  - export PIP_USE_MIRRORS=true

install:
  - pip install pipenv
  - pipenv install
  - pipenv shell
  - server/manage.py migrate
  - server/manage.py loaddata users datasets analyses files

after_success:
  - coveralls

script:
  - pylint server/
  - nosetests

deploy:
  provider: heroku
  api_key: app:36d0606c-a518-47e5-b60c-2eff8e678f40
  app:
    master: crux-staging-nebigdatahub
    production: crux-staging-nebigdatahub

notifications:
  email:
    - raphnano@gmail.com
    - acm2248@columbia.edu